import { Exercise } from './workoutTypes';

/**
 * 30 Seed Exercises standardizing Samsung Health categories
 * MET values sourced from 2011 Compendium of Physical Activities (Ainsworth et al.)
 */
export const SEED_EXERCISES: Exercise[] = [
  // 1. Chung (General)
  {
    id: 'walking',
    name: 'Đi bộ',
    category: 'GENERAL',
    trackingType: 'DISTANCE_GPS',
    met: 3.5,
    iconName: 'Footprints',
    isSystem: true,
    isFavorite: true,
    defaultTargetType: 'NONE',
    description: 'Đi bộ tự nhiên giúp tăng cường tuần hoàn máu và thư giãn tinh thần.',
  },
  {
    id: 'combined_workout',
    name: 'Bài tập kết hợp',
    category: 'GENERAL',
    trackingType: 'TIME_CALORIES',
    met: 5.0,
    iconName: 'Dumbbell',
    isSystem: true,
    defaultTargetType: 'NONE',
    description: 'Tổ hợp các động tác thể chất rèn luyện sức bền và toàn thân.',
  },
  {
    id: 'stretching',
    name: 'Giãn cơ',
    category: 'GENERAL',
    trackingType: 'TIME_CALORIES',
    met: 2.5,
    iconName: 'Sparkles',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 15,
    description: 'Kéo giãn cơ bắp, hỗ trợ phục hồi và tăng tính linh hoạt của khớp.',
  },
  {
    id: 'yoga',
    name: 'Yoga',
    category: 'GENERAL',
    trackingType: 'TIME_CALORIES',
    met: 3.0,
    iconName: 'HeartPulse',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 30,
    description: 'Tập trung hơi thở, kéo giãn và cân bằng năng lượng cơ thể.',
  },
  {
    id: 'calisthenics',
    name: 'Thể dục tại chỗ',
    category: 'GENERAL',
    trackingType: 'TIME_CALORIES',
    met: 4.0,
    iconName: 'Activity',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 20,
    description: 'Tập các động tác cơ bản dùng trọng lượng cơ thể không cần dụng cụ.',
  },

  // 2. Hiếu khí (Aerobic / Cardio)
  {
    id: 'running',
    name: 'Chạy bộ',
    category: 'AEROBIC',
    trackingType: 'DISTANCE_GPS',
    met: 7.5,
    iconName: 'Flame',
    isSystem: true,
    isFavorite: true,
    defaultTargetType: 'NONE',
    description: 'Chạy bộ ngoài trời rèn luyện sức bền tim mạch và đốt cháy calo cao.',
  },
  {
    id: 'cycling',
    name: 'Đạp xe',
    category: 'AEROBIC',
    trackingType: 'DISTANCE_GPS',
    met: 6.0,
    iconName: 'Bike',
    isSystem: true,
    isFavorite: true,
    defaultTargetType: 'NONE',
    description: 'Đạp xe ngoài trời tăng cường cơ chân và tuần hoàn tim phổi.',
  },
  {
    id: 'treadmill',
    name: 'Máy chạy bộ',
    category: 'AEROBIC',
    trackingType: 'TIME_CALORIES',
    met: 7.0,
    iconName: 'Gauge',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 30,
    description: 'Chạy bộ trên máy trong nhà, kiểm soát tốc độ và độ dốc.',
  },
  {
    id: 'elliptical',
    name: 'Máy tập elip',
    category: 'AEROBIC',
    trackingType: 'TIME_CALORIES',
    met: 5.0,
    iconName: 'RotateCw',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 20,
    description: 'Vận động toàn thân nhịp nhàng, giảm tối đa áp lực lên khớp gối.',
  },
  {
    id: 'jump_rope',
    name: 'Nhảy dây',
    category: 'AEROBIC',
    trackingType: 'TIME_CALORIES',
    met: 8.8,
    iconName: 'Zap',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 15,
    description: 'Đốt mỡ cực nhanh, tăng khả năng phối hợp nhịp điệu và sức bật.',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'AEROBIC',
    trackingType: 'SETS_REST',
    met: 8.0,
    iconName: 'Flame',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Bài tập toàn thân cường độ cao kết hợp hít đất và bật nhảy.',
  },
  {
    id: 'aerobic_dance',
    name: 'Aerobic',
    category: 'AEROBIC',
    trackingType: 'TIME_CALORIES',
    met: 6.5,
    iconName: 'Music',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 30,
    description: 'Nhảy thể dục nhịp điệu theo điệu nhạc sôi động.',
  },

  // 3. Tập tạ tự do (Free Weights)
  {
    id: 'push_up',
    name: 'Hít đất',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 4.0,
    iconName: 'Shield',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Phát triển cơ ngực, vai trước và tay sau bằng trọng lượng cơ thể.',
  },
  {
    id: 'squats',
    name: 'Squats',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 5.0,
    iconName: 'ArrowDownCircle',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Bài tập vua cho thân dưới, phát triển cơ đùi trước, đùi sau và cơ mông.',
  },
  {
    id: 'lunges',
    name: 'Bài tập chùng chân',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 4.0,
    iconName: 'ChevronDown',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Tăng cường sức mạnh từng chân độc lập và cải thiện thăng bằng.',
  },
  {
    id: 'crunches',
    name: 'Gập bụng',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 3.8,
    iconName: 'Disc',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Tác động trực tiếp lên nhóm cơ bụng trên và cơ lõi trung tâm.',
  },
  {
    id: 'dumbbell_curl',
    name: 'Tập tạ tay',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 4.0,
    iconName: 'Dumbbell',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 4,
    description: 'Rèn luyện cơ bắp tay trước với tạ đơn (Dumbbells).',
  },
  {
    id: 'pull_up',
    name: 'Hít xà đơn',
    category: 'FREE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 5.5,
    iconName: 'ArrowUpCircle',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Phát triển cơ xô, lưng trên và tay trước vượt trội.',
  },

  // 4. Tập tạ với máy (Weight Machines)
  {
    id: 'lat_pulldown',
    name: 'Kéo xô với máy',
    category: 'MACHINE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 4.5,
    iconName: 'Layers',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Rèn luyện độ rộng của cơ lưng xô an toàn trên khung máy kéo cáp.',
  },
  {
    id: 'leg_press',
    name: 'Đạp đùi với máy',
    category: 'MACHINE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 5.0,
    iconName: 'Box',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 4,
    description: 'Tác động lực lớn lên toàn bộ nhóm cơ chân mà không đè nặng lên cột sống.',
  },
  {
    id: 'chest_press_machine',
    name: 'Đẩy ngực với máy',
    category: 'MACHINE_WEIGHT',
    trackingType: 'SETS_REST',
    met: 4.0,
    iconName: 'Target',
    isSystem: true,
    defaultTargetType: 'SETS',
    defaultTargetValue: 3,
    description: 'Tập ngực ổn định theo quỹ đạo chuyển động định sẵn của máy.',
  },

  // 5. Vùng hoang dã (Wilderness / Outdoor)
  {
    id: 'hiking',
    name: 'Đi bộ đường dài',
    category: 'WILDERNESS',
    trackingType: 'DISTANCE_GPS',
    met: 6.0,
    iconName: 'Compass',
    isSystem: true,
    defaultTargetType: 'DISTANCE',
    defaultTargetValue: 5,
    description: 'Đi bộ dã ngoại trên địa hình dốc gập ghềnh hòa mình với thiên nhiên.',
  },
  {
    id: 'trail_running',
    name: 'Chạy địa hình',
    category: 'WILDERNESS',
    trackingType: 'DISTANCE_GPS',
    met: 8.5,
    iconName: 'Mountain',
    isSystem: true,
    defaultTargetType: 'DISTANCE',
    defaultTargetValue: 5,
    description: 'Chạy bộ đường đồi núi đòi hỏi thể lực cao và phản xạ chân linh hoạt.',
  },

  // 6. Nước (Water)
  {
    id: 'pool_swimming',
    name: 'Bơi hồ bơi',
    category: 'WATER',
    trackingType: 'TIME_CALORIES',
    met: 6.0,
    iconName: 'Waves',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 30,
    description: 'Bơi lội trong bể bơi tiêu chuẩn, phát triển toàn diện hệ cơ và dung tích phổi.',
  },
  {
    id: 'open_water_swimming',
    name: 'Bơi ngoài trời',
    category: 'WATER',
    trackingType: 'DISTANCE_GPS',
    met: 7.0,
    iconName: 'SunMedium',
    isSystem: true,
    defaultTargetType: 'DISTANCE',
    defaultTargetValue: 1,
    description: 'Bơi ở biển, hồ tự nhiên với điều kiện sóng nước thử thách.',
  },

  // 7. Mùa đông (Winter)
  {
    id: 'skiing',
    name: 'Trượt tuyết',
    category: 'WINTER',
    trackingType: 'DISTANCE_GPS',
    met: 7.0,
    iconName: 'Snowflake',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 60,
    description: 'Trượt dốc tuyết rèn luyện thăng bằng và sức chịu đựng thời tiết lạnh.',
  },
  {
    id: 'ice_skating',
    name: 'Trượt băng',
    category: 'WINTER',
    trackingType: 'TIME_CALORIES',
    met: 6.0,
    iconName: 'CloudSnow',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 45,
    description: 'Lướt trên mặt băng uyển chuyển, phát triển cơ bắp chân và cơ lõi.',
  },

  // 8. Bóng (Ball Sports)
  {
    id: 'badminton',
    name: 'Cầu lông',
    category: 'BALL',
    trackingType: 'TIME_CALORIES',
    met: 5.5,
    iconName: 'Trophy',
    isSystem: true,
    defaultTargetType: 'NONE',
    description: 'Môn thể thao đối kháng tốc độ cao, phản xạ nhanh và di chuyển liên tục.',
  },
  {
    id: 'table_tennis',
    name: 'Bóng bàn',
    category: 'BALL',
    trackingType: 'TIME_CALORIES',
    met: 4.0,
    iconName: 'CircleDot',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 45,
    description: 'Rèn luyện phản xạ thị giác và sự khéo léo của cổ tay.',
  },
  {
    id: 'soccer',
    name: 'Bóng đá',
    category: 'BALL',
    trackingType: 'DISTANCE_GPS',
    met: 7.5,
    iconName: 'Goal',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 60,
    description: 'Môn thể thao vua, chạy nước rút liên tục rèn luyện sức bền tim mạch.',
  },
  {
    id: 'volleyball',
    name: 'Bóng chuyền',
    category: 'BALL',
    trackingType: 'TIME_CALORIES',
    met: 4.0,
    iconName: 'Globe',
    isSystem: true,
    defaultTargetType: 'TIME',
    defaultTargetValue: 45,
    description: 'Bật nhảy, đập bóng và phối hợp đồng đội năng động.',
  },
];
